### ISSUE TITLE
Sorry I'm really confused and new to Playnite, how do I fix this?

### ISSUE THREAD

**Issue by RorschachsDream** [darklinkpower/Nova-X#10]
I prefer to use the Details view and I love this theme so much but I was wondering if there's a way I can remove this blank space at the top of the game list? The area enclosed in blue here:

![Untitled](https://github.com/darklinkpower/Nova-X/assets/96325004/e46776bd-dfa3-428b-8731-67f017dec57d)

That way my games list starts right at the top of the screen rather than part way down?

**Comment by darklinkpower** [comment]
Replace `Margin="{DynamicResource PanelTopPanelSeparator}"` to `Margin="0"` here in your local theme file installation: https://github.com/darklinkpower/Nova-X/blob/50986d6f793632bade544c55cdbd29997e5fff8c/source/Views/LibraryDetailsView.xaml#L32

To go there: Main menu -> Add-ons -> Installed -> Themes Desktop -> Nova X and click "Installation folder" on the right.

**Comment by RorschachsDream** [comment]
Thank you, worked perfectly and looks so much better (IMO)! Thank you for the theme in general tho. ^_^
