### ISSUE TITLE
Increase Description size

### ISSUE THREAD

**Issue by Wpnnt** [darklinkpower/Nova-X#12]
### Feature Description

There a way to increase description size ? because cant see full description without scrolling.
![image_2024-10-14_174354634](https://github.com/user-attachments/assets/dc52e1a1-4027-4d18-9e84-05ab893e47b0)

**Comment by darklinkpower** [comment]
I've added an option to set the maximum height in a new update, can be changed using the ThemeModifier extension:

![image](https://github.com/user-attachments/assets/02084869-1018-4279-b366-b85486e201ea)

**Comment by Wpnnt** [comment]
Thank you!
