### ISSUE TITLE
Howlongtobeat Data Window, Bottom Right Corner Button Bug

### ISSUE THREAD

**Issue by Gous4** [darklinkpower/Nova-X#13]
### Bug Description

When I want to add HowLongtoBeat Data, this window has a Bug where in the Bottom Right Corner 2 Buttons are not Shown Correctly.

### Screenshots

![Screenshot 2024-12-11 155305](https://github.com/user-attachments/assets/77001797-c3da-4fce-920b-1dd30e8848ef)

**Comment by darklinkpower** [comment]
Extension issue: https://github.com/Lacro59/playnite-howlongtobeat-plugin/issues/235
