### ISSUE TITLE
Cannot replicate one of the screenshots

### ISSUE THREAD

**Issue by aacmnv** [darklinkpower/Nova-X#5]
### Bug Description

I have tried searching everywhere, and I copied you settings in the readme file but I cannot replicate the screenshot shown in this issue. Please tell me or include in the readme file how to make the right side big.

Your one:
![image](https://github.com/darklinkpower/Nova-X/assets/100611954/e3b84642-127b-44ec-bf45-2b7bafadaa5c)

My one:
![Screenshot 2024-02-08 165100](https://github.com/darklinkpower/Nova-X/assets/100611954/1cc1da81-9666-43b2-9b2b-cdff3e0f0977)

### Screenshots

![image](https://github.com/darklinkpower/Nova-X/assets/100611954/cd8830b6-232d-48ef-aa20-7e6244bf3d37)

**Comment by darklinkpower** [comment]
I apologize for the late reply. You need to install this extension, enable this theme in its settings afterwards, restart and then increase the Grid View details width in Playnite settings under layout.

https://playnite.link/addons.html#ThemesDetailsViewToGridViewConverter_ef8a7226-eedc-478d-a506-92ee6c088aa3
