### ISSUE TITLE
Suggestions for tiny (as in nitpicky) visual improvements

### ISSUE THREAD

**Issue by Super1337Boy** [darklinkpower/Nova-X#9]
### Bug Description

First I just want to say that I love the Nova X theme!

I just wanted to add a few suggestions for tiny visual improvements. I've pointed them out in the attached images.

Edit: Sorry, I just realized this should probably have been labeled "enhancement" instead of "bug". I don't think it's possible for me to change that, but I don't mind closing the issue and making a new one if you want.

### Screenshots

![Improvement_suggestions](https://github.com/darklinkpower/Nova-X/assets/6672819/6ae53af2-35a6-4a8e-a2e0-1f5215a1d716)

![Improvement_suggestions_2](https://github.com/darklinkpower/Nova-X/assets/6672819/4d5557fb-6e00-483f-bed7-d5debf0af82e)

**Comment by darklinkpower** [comment]
Fixed in latest update.
